version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog..."
      - pip install --upgrade pip
      - pip install truffleHog
      - yum install -y jq
  
  pre_build:
    commands:
      - echo "Starting TruffleHog secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "Repository files to scan:"
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.env" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog secret scan..."
      - trufflehog filesystem . --json > trufflehog-results.json 2>&1 || scan_failed=$?
      - echo "Scan completed with exit code ${scan_failed:-0}"
      - echo "Scan results:"
      - cat trufflehog-results.json 2>/dev/null || echo "No JSON results"
      - |
        if [ "${scan_failed:-0}" != "0" ]; then
          echo "SECRETS DETECTED"
          SECRET_FILES=$(find . -name "*.env" -o -name "*secrets*" -o -name "config.txt" | tr '\n' ', ' | sed 's/,$//' || echo "demo.env, demo_secrets.py")
          echo "SECURITY_STATUS=FAILED" > scan-status.txt
          echo "SECRET_FILES=${SECRET_FILES}" >> scan-status.txt
          echo "Secrets found in: ${SECRET_FILES}"
        else
          echo "No secrets found"
          echo "SECURITY_STATUS=PASSED" > scan-status.txt
          echo "SECRET_FILES=" >> scan-status.txt
        fi

artifacts:
  files:
    - trufflehog-results.json
    - scan-status.txt
  name: security-scan-results