version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog..."
      - pip install --upgrade pip
      - pip install truffleHog
  
  pre_build:
    commands:
      - echo "Starting TruffleHog secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "=== REPOSITORY STRUCTURE ==="
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog scan..."
      - trufflehog filesystem . --json > trufflehog-results.json || true
      - echo "=== SCAN RESULTS ==="
      - cat trufflehog-results.json || echo "No results file"
      - if [ -s trufflehog-results.json ]; then echo "SECRETS DETECTED"; exit 1; fi
  
  post_build:
    commands:
      - echo "Secret detection scan completed successfully"
      - echo "No secrets found in repository"

artifacts:
  files:
    - trufflehog-results.json
  name: security-scan-results