version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog..."
      - pip install --upgrade pip
      - pip install truffleHog
  
  pre_build:
    commands:
      - echo "Starting TruffleHog secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "=== REPOSITORY STRUCTURE ==="
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog scan..."
      - trufflehog filesystem . --json --fail > trufflehog-results.json 2>&1 || scan_failed=$?
      - echo "=== SCAN RESULTS ==="
      - cat trufflehog-results.json 2>/dev/null || echo "No JSON results"
      - echo "=== SCAN EXIT CODE: ${scan_failed:-0} ==="
      - if [ "${scan_failed:-0}" != "0" ]; then echo "SECRETS DETECTED - BUILD FAILED"; exit 1; fi
  
  post_build:
    commands:
      - echo "Secret detection scan completed successfully"
      - echo "No secrets found in repository"

artifacts:
  files:
    - trufflehog-results.json
  name: security-scan-results