version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog..."
      - pip install --upgrade pip
      - pip install truffleHog
  
  pre_build:
    commands:
      - echo "Starting TruffleHog secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "=== REPOSITORY STRUCTURE ==="
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.env" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog scan..."
      - trufflehog filesystem . --json > trufflehog-results.json 2>&1 || scan_failed=$?
      - echo "=== SCAN RESULTS ==="
      - cat trufflehog-results.json 2>/dev/null || echo "No JSON results"
      - echo "=== SCAN EXIT CODE ${scan_failed:-0} ==="
      - |
        if [ "${scan_failed:-0}" != "0" ]; then
          echo "SECRETS DETECTED - BUILD FAILED"
          SECRET_FILES=$(cat trufflehog-results.json 2>/dev/null | grep -o '"SourceMetadata":{[^}]*"file":"[^"]*"' | grep -o '"file":"[^"]*"' | cut -d'"' -f4 | sort -u | tr '\n' ', ' | sed 's/,$//')
          MESSAGE="ALERT: Secrets detected in files: ${SECRET_FILES:-unknown files}. Build failed."
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:361509912577:ml-secrets-demo-pipeline-notifications" --message "$MESSAGE" --subject "Secret Detection Alert" || true
          exit 1
        else
          echo "No secrets found"
        fi

artifacts:
  files:
    - trufflehog-results.json
  name: security-scan-results