version: 0.2

phases:
  build:
    commands:
      - echo "Processing security scan results..."
      - |
        if [ -f "scan-status.txt" ]; then
          source scan-status.txt
          echo "Security Status: $SECURITY_STATUS"
          echo "Affected Files: $SECRET_FILES"
          
          if [ "$SECURITY_STATUS" = "FAILED" ]; then
            MESSAGE="SECURITY ALERT: Secrets detected in files: ${SECRET_FILES}. Deployment should be blocked."
            aws sns publish --topic-arn "$SNS_TOPIC_ARN" --message "$MESSAGE" --subject "Secret Detection Alert" || true
            echo "Security violation notification sent"
            exit 1
          else
            MESSAGE="Security scan passed. No secrets detected. Safe to deploy."
            aws sns publish --topic-arn "$SNS_TOPIC_ARN" --message "$MESSAGE" --subject "Security Scan Success" || true
            echo "Success notification sent"
          fi
        else
          echo "No scan status file found"
          aws sns publish --topic-arn "$SNS_TOPIC_ARN" --message "Security scan completed but status unknown" --subject "Security Scan Update" || true
        fi

artifacts:
  files:
    - scan-status.txt
  name: notification-complete