version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog..."
      - pip install --upgrade pip
      - pip install truffleHog
      - yum install -y jq
  
  pre_build:
    commands:
      - echo "Starting TruffleHog secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "Repository files to scan:"
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.env" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog secret scan..."
      - trufflehog filesystem . --json > trufflehog-results.json 2>&1 || scan_failed=$?
      - echo "Scan completed with exit code ${scan_failed:-0}"
      - echo "Scan results:"
      - cat trufflehog-results.json 2>/dev/null || echo "No JSON results"
      - |
        if [ "${scan_failed:-0}" != "0" ]; then
          echo "SECRETS DETECTED"
          SECRET_FILES=$(find . -name "*.env" -o -name "*secrets*" -o -name "config.txt" | tr '\n' ', ' | sed 's/,$//' || echo "demo.env, demo_secrets.py")
          MESSAGE="SECURITY ALERT: Secrets detected in files: ${SECRET_FILES}. Build failed. Check CodeBuild logs for details."
          echo "Sending notification: $MESSAGE"
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:361509912577:ml-secrets-demo-pipeline-notifications" --message "$MESSAGE" --subject "Secret Detection Alert" || true
          exit 1
        else
          echo "No secrets found"
        fi

artifacts:
  files:
    - trufflehog-results.json
  name: security-scan-results