version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing TruffleHog scanner..."
      - pip install --upgrade pip
      - pip install truffleHog
      - echo "TruffleHog installation complete"
  
  pre_build:
    commands:
      - echo "Preparing secret detection scan..."
      - echo "Project $PROJECT_NAME"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "Repository files to scan:"
      - find . -type f -name "*.py" -o -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.env" | head -20
  
  build:
    commands:
      - echo "Running TruffleHog secret scan..."
      - trufflehog filesystem . --json > trufflehog-results.json 2>&1 || scan_exit_code=$?
      - echo "Scan completed with exit code ${scan_exit_code:-0}"
      - echo "Raw scan results:"
      - cat trufflehog-results.json 2>/dev/null || echo "No results file generated"
      - echo "Security scan stage complete"

artifacts:
  files:
    - trufflehog-results.json
  name: scan-results-artifact